# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  docker: circleci/docker@1.4.0
  aws-ecr: circleci/aws-ecr@6.12.2
  slack: circleci/slack@4.2.1
  aws-s3: circleci/aws-s3@1.0.16
  packer: salaxander/packer@0.0.3
  aws-cli: circleci/aws-cli@1.3.1 

executors:
  test-executor:
    # Please don't use xlarge resource classes before approving, they consume 5x credits compared to large
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true

jobs:
  build:
    executor: test-executor
    steps:
      - checkout
      - run: echo 0
 
  job2:
    executor: test-executor
    steps:
      - checkout
  job3:
    executor: test-executor
    steps:
      - checkout
  job4:
    executor: test-executor
    steps:
      - checkout
  job5:
    executor: test-executor
    steps:
      - checkout
  job6:
    executor: test-executor
    steps:
      - checkout

workflows:
  workflow1:
    jobs:
      - build
      - job2
      - job6:
          requires:
            - build
            - job2
            - job3
            - job4
            - job5
